require('options')
require('neovide')
require('plugins')
require('lualineconfig')
require('colourscheme')
require('customcommands')
require('cmpConfig')
require('lsp')
require('TreesitterConfig')
require('keybind')
-- require('noiceconfig')
