require('options')
require('neovide')
require('plugins')
require('lualineconfig')
require('colourscheme')
require('cmpConfig')
require('lsp')
require('TreesitterConfig')
require('keybind')
require('customcommands')
-- require('noiceconfig')
vim.cmd([[command! ReloadConf luafile ~/.config/nvim/init.lua]])
-- vim.cmd([[command! ReloadConfCommands luafile ~/.config/nvim/lua/customcommands.lua]])

