require('config.lazy')
require('options')
-- require('neovide')
-- require('plugins')
-- require('iron')
require('colourscheme')
require('customcommands')
-- require('cmpConfig')
-- require('lsp')
-- require('TreesitterConfig')
--
-- require("mason").setup()
require('keybind')
-- require('noiceconfig')
