vim.opt.autoindent = true			-- Autoindent
vim.opt.smartindent = true 			-- Autoindent
vim.opt.tabstop = 4						-- tab
vim.opt.shiftwidth = 4
vim.opt.showtabline = 4
vim.opt.expandtab = true
vim.opt.smd = false 					--turn off mode mesage
vim.opt.nu = true 						-- number
vim.opt.rnu = true 						-- relative number
vim.opt.ignorecase = true			--ignore case on search
vim.opt.smartcase = true			--ignore case only if all lower
vim.opt.scrolloff = 8					--scroll off amount
vim.opt.incsearch = true			-- search incremently
vim.opt.hlsearch = true				-- highlight search as you type
vim.opt.mouse = "a"						-- where you can use mouse
vim.opt.swapfile = false			-- swapfile
vim.opt.guifont = {"CaskaydiaCove NF",":h12"} --font in gui environments "Font:fontsize"
vim.opt.termguicolors = true
vim.opt.laststatus=3
vim.opt.filetype = 'on'
-- Global Options
vim.g.noru = true 						-- turno off ruler
vim.g.netrw_winsize = 20
